Repository FaithsCoding/weather-i-go, pull requests merged in 2023-03, with the labels that each got.

#18 15 we need the basic html markup semantic please
  .DS_Store
  index.html
Labels: documentation

#30 Added Github links & NavBar
  .DS_Store
  .vscode/settings.json
  index.html
Labels: documentation

#32 added styling
  assets/css/style.css
Labels: documentation

#33 changes made to footer
  index.html
Labels: documentation

#36 start to central section
  index.html
Labels: PLEASE APPROVE

#38 modals added to modal.js for reference
  assets/js/modals.js
  index.html
Labels: PLEASE APPROVE

#45 Added HEADER, PLACEHOLDER and BULMA to elements
  index.html
Labels: documentation, enhancement, PLEASE APPROVE

#50 Added 6 cards as per wireframe and a margin in css file
  assets/css/style.css
  index.html
Labels: documentation, PLEASE APPROVE

#53 Just merge the base
  assets/css/style.css
  assets/js/modals.js
  index.html
Labels: AUTOMATIC MERGE

#54 MEGA MERGER - 51 add ticket master api functionality & more
  assets/css/style.css
  assets/js/errorhandler.js
  assets/js/googelapi.js
  assets/js/modals.js
  assets/js/script.js
  index.html
Labels: enhancement, TEST PHASE, PLEASE APPROVE

#62 changed folder name
  images/Rocketlogo.png
  images/weatherlogo.png
Labels: documentation

#71 67 make map appear below search form
  assets/css/style.css
  assets/images/Rocketlogo.png
  assets/images/weatherlogo.png
  assets/js/cards.js
  assets/js/googelapi.js
  assets/js/modals.js
  assets/js/script.js
  index.html
Labels: documentation, PLEASE APPROVE

#74 41 increment form handling
  assets/js/script.js
  assets/js/weatherapi.js
Labels: PLEASE APPROVE

#75 72 fix todays version before we pull
  assets/js/modals.js
  assets/js/weatherapi.js
  index.html
Labels: PLEASE APPROVE

#81 Wrapup
  assets/css/style.css
  assets/js/cards.js
  assets/js/googelapi.js
  assets/js/script.js
  assets/js/ticketmaster.js
  assets/js/weatherapi.js
  index.html
Labels: PLEASE APPROVE
